// react/src/Video/index.jsx
import React, { Component } from 'react'
import DCE from '../dce'
import './index.css'

export default class index extends Component {
    componentDidMount() {
        this.initSettings()
    }

    initSettings = async () => {
        window.enhancer = await window.DCE.createInstance();
        const callbackCameraOpen = () => {
            console.log("camera opened");
        };
        // if close camera, should set the selection box to not selectable
        const callbackCameraClose = () => {
            this.props.changeDisabled()
            console.log("camera closeed");
        };
        const callbackCameraChange = () => { 
            console.log("camera changed");
        };
        const callbackResolutionChange = () => {
            console.log("camera resolution changed");
        };
        window.enhancer.on("cameraOpen", callbackCameraOpen);
        window.enhancer.on("cameraClose", callbackCameraClose);
        window.enhancer.on("cameraChange", callbackCameraChange);
        window.enhancer.on("resolutionChange", callbackResolutionChange);
    }

    render() {
        return (
            <div id="recognizerUI"></div>
        )
    }
}

// vue3+typescript/src/components/Video.vue
<template>
    <div id="recognizerUI"></div>
</template>

<script lang="ts">
import { onMounted } from '@vue/runtime-core';
import { useStore } from 'vuex',
import DCE from '../dce'
export default {
    name: 'Video',
    setup() {
        const store = useStore()
        
        let initSettings = async () => {
            (window as any).enhancer = await DCE.createInstance();
            const callbackCameraOpen = ():void => {
                console.log("camera opened");
            };
            // if close camera, should set the selection box to not selectable
            const callbackCameraClose = ():void => {
                console.log("camera closeed");
                store.state.decoratorIsDisabled = true;
                store.state.lineWidthIsDisabled = true;
                store.state.strokeStyleIsDisabled = true;
                store.state.fillStyleIsDisabled = true;
                store.state.maskFillStyleIsDisabled = true;
            };
            const callbackCameraChange = ():void => { 
                console.log("camera changed");
            };
            const callbackResolutionChange = ():void => {
                console.log("camera resolution changed");
            };
            (window as any).enhancer.on("cameraOpen", callbackCameraOpen);
            (window as any).enhancer.on("cameraClose", callbackCameraClose);
            (window as any).enhancer.on("cameraChange", callbackCameraChange);
            (window as any).enhancer.on("resolutionChange", callbackResolutionChange); 
        }

        onMounted(() => {
            initSettings()
        })
    },
}
</script>

<style lang="less" scoped>
#recognizerUI {
    position: absolute;
    top: 0;
    bottom: 30%;
    left: 0;
    right: 0;
}
</style>
